### ISSUE TITLE
SwissGeol Terrain Fails to Load Due to CORS Error

### ISSUE THREAD

**Issue by Masty88** [swisstopo/swissgeol-viewer-app#1356]
The SwissGeol terrain is failing to load in the official SwissGeol viewer when attempting to use the 'cli_terrain_ch-2m' option. This issue appears to be related to a CORS (Cross-Origin Resource Sharing) error when trying to access the terrain data.

**Steps to Reproduce:**
Visit the SwissGeol viewer: https://viewer.swissgeol.ch/
Add the following parameters to the URL:
`https://viewer.swissgeol.ch/?lang=fr&lon=7.20160&lat=45.93609&elevation=22260&heading=6&pitch=-62&map=lakes_rivers_map&map_transparency=0.00&ownterrain=cli_terrain_ch-2m`

Note the CORS error related to terrain loading

**Comment by nOester** [comment]
@Masty88 
Thanks for your message.
I'll take this bug into our planning. We are currently reworking our deploy prozess, after finshing it we will deploy the fix.
Bet regards
Nils

**Comment by daniel-va** [comment]
@nOester I'm currently not able to reproduce this issue. The query given above does not produce any network errors on my side.

**Comment by Masty88** [comment]
@daniel-va @nOester  yes i can confirm the cors error seem to be fixed  in the meantime thank you for checking this i will close this issue
